version: '3'
services:
  ssd-det:
    # network_mode: "host"
    build: .
    command: python -u app.py
    ports:
      - "80:5000"
    volumes:
      - .:/ssd-det
      - ../uploads:/uploadsD
      - ./stable-diffusion-v1-4:/ssd-det/stable-diffusion-v1-4
    environment:
      - MONGO_DATABASE=viva-api-responses
      - MONGO_USERNAME=apiBackend
      - MONGO_PASSWORD=apiBackendPwd
    deploy:
        resources:
            limits:
                cpus: "0.50"
                memory: 2000M
            reservations:
                cpus: "0.25"
                memory: 500M

    # links:
    #   - db
  
  # db:
  #   image: mongo:latest
  #   hostname: test_mongodb
  #   environment:
  #     - MONGO_INITDB_DATABASE=animal_db
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=pass
  #   volumes:
  #     - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  #   ports:
  #     - 27017:27017

      # docker compose up -d --build
